logging:
  config: classpath:log/log4j2-dev.xml

spring.session.redis.flush-mode: on_save
spring.session.store-type: redis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      database-platform: MYSQL
  aop:
    proxy-target-class: true
  redis:
    host: localhost
    password: test123
    port: 6379
    database: 10
  freemarker:
    cache: false
    charset: utf-8
    content-type: text/html
    check-template-location: true
    suffix: .html
    #expose-request-attributes: true
    ##expose-session-attributes: true
    #request-context-attribute: request


server:
  port: 12345